version: '3.8'

services:
  weather-api:
    image: weather-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"
    restart: always
    networks:
      - weather-net

networks:
  weather-net:
    driver: bridge