name: Deploy to AKS

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_CLUSTER_NAME }} \
            --overwrite-existing

      - name: Install helm
        uses: azure/setup-helm@v3

      - name: Deploy secrets
        run: |
          WEATHER_API_KEY=$(echo -n "${{ secrets.WEATHER_API_KEY }}" | base64)
          DATABASE_URL=$(echo -n "${{ secrets.DATABASE_URL }}" | base64)
          envsubst < k8s/secrets/weather-api-secrets.yaml.tpl > secrets.yaml
          kubectl apply -f secrets.yaml -n ${{ secrets.K8S_NAMESPACE }}

      - name: Deploy application
        run: |
          kubectl apply -f k8s/manifests/weather-api/ -n ${{ secrets.K8S_NAMESPACE }}

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/weather-api -n ${{ secrets.K8S_NAMESPACE }}
          kubectl get pods -n ${{ secrets.K8S_NAMESPACE }}